AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'Gemfile'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  EnforcedStyle: compact

StringLiterals:
  EnforcedStyle: double_quotes

MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Enabled: true
  Max: 20
