version: '3.8'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/BookManager-server
      - bundle:/bundle
    depends_on:
      - db
    command: ["rails", "server", "-b", "0.0.0.0"]
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0.21
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'BookManager_server_development'
    ports:
      - '4306:3306'        
  
  test-db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'password_test'
      MYSQL_ROOT_PASSWORD: 'root_test'
      MYSQL_DATABASE: 'BookManager_server_test'
    ports: 
      - '5306:3306'

volumes:
  mysql_data:
    driver: local
  bundle:
    driver: local        
                
                
      

